version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP bağlantı noktası
      - "15672:15672"  # Yönetim paneli için port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Redis portu
    restart: unless-stopped
